### ISSUE TITLE
Zookeeper filesystem remounted as read-only

### ISSUE THREAD

**Issue by bbranan** [hybox/aws#165]
This issue has come up twice so far, once on 7/6/2017 and again on 8/15/2017, both in the pilot AWS stack.

The issue: The filesystem under the zookeeper docker container is remounted as read-only. When Zookeeper attempts to write to a file it fails to do so [1] and Zookeeper becomes unresponsive. Exhibitor then restarts Zookeeper on that instance which starts successfully up to the point where it attempts to write a file, at which point it fails again. Exhibitor then restarts it again and the cycle continues indefinitely. Each time Zookeeper is restarted it joins the Zookeeper Ensemble with the rest of the nodes then drops out again when it fails. Each change to the set of nodes in the Ensemble causes Exhibitor to restart each of the other Zookeeper nodes. This constant restarting of all of the Zookeeper nodes results in a Solr being unavailable or slow to respond to the Hyku app, making the app effectively unusable.

Work around: The immediate fix for this problem is to terminate the failing Zookeeper node. Auto-scaling will start another instance which will be added and the Ensemble will recover normal functionality.

The question is: Why is the filesystem being remounted as read-only, and how to prevent this from happening?

[1] 
```
Aug 14, 2017 9:03:33 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
INFO  com.netflix.exhibitor.core.activity.ActivityLog  State: down [ActivityQueue-0]
INFO  com.netflix.exhibitor.core.activity.ActivityLog  Server list has changed [ActivityQueue-0]
INFO  com.netflix.exhibitor.core.activity.ActivityLog  Attempting to stop instance [ActivityQueue-0]
INFO  com.netflix.exhibitor.core.activity.ActivityLog  Attempting to start/restart ZooKeeper [ActivityQueue-0]
INFO  com.netflix.exhibitor.core.activity.ActivityLog  jps didn't find instance - assuming ZK is not running [ActivityQueue-0]
INFO  com.netflix.exhibitor.core.activity.ActivityLog  Starting in standalone mode [ActivityQueue-0]
ERROR com.netflix.exhibitor.core.activity.ActivityLog  Could not delete ID file: /opt/zookeeper/snapshots/myid [ActivityQueue-0]
ERROR com.netflix.exhibitor.core.activity.ActivityLog  Monitoring instance [ActivityQueue-0]
java.io.FileNotFoundException: /opt/zookeeper/conf/zoo.cfg (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:160)
        at com.netflix.exhibitor.core.processes.StandardProcessOperations.prepConfigFile(StandardProcessOperations.java:167)
        at com.netflix.exhibitor.core.processes.StandardProcessOperations.startInstance(StandardProcessOperations.java:109)
        at com.netflix.exhibitor.core.state.KillRunningInstance.completed(KillRunningInstance.java:41)
        at com.netflix.exhibitor.core.activity.ActivityQueue$1.run(ActivityQueue.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Aug 14, 2017 9:04:03 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 30.
```

**Comment by bbranan** [comment]
Discussion here: https://github.com/moby/moby/issues/18010 suggests that the root problem (the filesystem is getting remounted as read-only) may be a problem with the Docker config:
> One possibility is that thin pool got full. In that case ext4 will remount container rootfs read only. You will have to grow the size of loop back files and restart docker and that should grow the thin pool and that should get you going again.

More reading on this here https://serverfault.com/questions/840937/aws-elasticbeanstalk-docker-thin-pool-getting-full-and-causing-re-mount-of-files points to:
> The root cause seems to be Docker not mounting its storage engine (thin-provisioned devicemapper by default in Elastic Beanstalk) with the discard options, which in turn fills blocks until it breaks.

Looking in the AWS docs here: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-storage-config.html
> Remove unused data blocks within containers. You can use the following command to run fstrim on any running container and discard any data blocks that are unused by the container file system.
`sudo sh -c "docker ps -q | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/"`

**Comment by bbranan** [comment]
Running `sudo docker info` provides verification that the docker data space is completely consumed:
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 12.73 GB
 Data Space Total: 12.73 GB
 Data Space Available: 0 B
```
Running `sudo grep -B10 "read-only" /var/log/messages` is an easy way to check if the docker file system has been converted to read-only status.

Using the command noted in the previous comment did indeed free up a considerable portion of data space:
`sudo sh -c "docker ps -q | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/"`

However, if the filesystem is already in a read-only state, this will not solve the problem. The simplest fix is to terminate the zookeeper instance and allow auto-scaling to launch a new one. This new instance will join the ensemble automatically.

**Comment by bbranan** [comment]
This issue continued to occur roughly 1-2 times weekly for over 2 months. Adding a cron script to run the `fstrim` command noted in the previous comment every 10 minutes proved to be of little benefit, as the docker data space continued to drop to 0 and be remounted as read-only.

The EBS volume attached for docker data space on the pilot stack was 12 GB. It appears that this size may have simply been too small. The demo stack, which was using 22 GB EBS volumes has not experienced this issue. After updating the AWS launch config (used by the auto-scaling group) to use 100 GB EBS volumes for storage at /dev/xvdcz (which is where ECS attaches docker storage using LVM), there have been no further occurrences of this problem. It has only been 1 week since this update, but there is no indication of data space being consumed without being released. The cron job noted above still runs every 10 minutes, which may account for some of the stability, but the larger storage space seems to have made the primary difference.

**Assuming these results continue, the CloudFormation stack change needed here is to ensure that the EBS volumes created for docker storage (and mounted to /dev/xvdcz) are 30+ GB in size.**

**Comment by bbranan** [comment]
For reference: The cron job referenced above to clean up docker data on the zookeeper nodes. The cron job outputs a log file `cleanDockerData.log` in /var/log, so the last component ensures this log file is rotated if it gets too large. Adding this to CloudFormation as a precaution wouldn't hurt:

`sudo nano /usr/local/bin/cleanDockerData.sh`

```
#!/bin/bash

date --iso-8601=seconds; sudo docker info | grep "Data Space"
sudo sh -c "docker ps -q | xargs docker inspect --format='{{ .State.Pid }}' | xargs -IZ fstrim /proc/Z/root/"
```

`sudo chmod +x /usr/local/bin/cleanDockerData.sh`
`sudo nano /etc/cron.d/cleanDocker`

```
*/10 * * * * root /usr/local/bin/cleanDockerData.sh >> /var/log/cleanDockerData.log 2>&1
```

`sudo nano /etc/logrotate.d/cleanDockerData`

```
/var/log/cleanDockerData.log {
    missingok
    notifempty
    size 100M
    yearly
    create 0644 root root
}
```
