### ISSUE TITLE
Solr not able to load config from Zookeeper

### ISSUE THREAD

**Issue by bbranan** [hybox/aws#166]
As listed here: https://app.honeybadger.io/projects/48327/faults/34032520, errors like:
`
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request Error: {metadata={error-class=org.apache.solr.common.SolrException,root-error-class=org.apache.zookeeper.KeeperException$ConnectionLossException},msg=Could not load collection from ZK
`
result in the Hyku app not being functional. While this could be due to #165 in this case it is not, as all Zookeeper nodes are running properly according to beanstalk and exhibitor. 

However, issue #165 has resulted in all zookeeper nodes being replaced recently, which https://issues.apache.org/jira/browse/SOLR-8868 suggests requires a Solr restart.

On restarting Solr, errors like the following show up in the logs (/var/log/containers):
```
2017-08-30 20:38:48.697 ERROR (coreContainerWorkExecutor-2-thread-1-processing-n:ip-10-0-3-106.ec2.internal:8983_solr) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [ffa8720f-fcfe-4978-941e-2a2f7ebcc6d8_shard1_replica1]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.solr.core.CoreContainer.lambda$load$6(CoreContainer.java:581)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.common.SolrException: Unable to create core [ffa8720f-fcfe-4978-941e-2a2f7ebcc6d8_shard1_replica1]
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:933)
        at org.apache.solr.core.CoreContainer.lambda$load$5(CoreContainer.java:553)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
        ... 5 more
Caused by: org.apache.solr.common.cloud.ZooKeeperException: Specified config does not exist in ZooKeeper: hyku
        at org.apache.solr.common.cloud.ZkStateReader.readConfigName(ZkStateReader.java:189)
        at org.apache.solr.cloud.CloudConfigSetService.createCoreResourceLoader(CloudConfigSetService.java:54)
        at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:74)
        at org.apache.solr.core.CoreContainer.create(CoreContainer.java:915)
```
At this point, Solr is running, but there are no loaded cores, so no data is available.

**Comment by bbranan** [comment]
RESOLUTION:
* The issue is that the set of configuration needed by solr, which is maintained by zookeeper, was lost by all of the zookeeper restarts
* These config files are on the hyku webapp server, and there is a rake task which can be used to push them to zookeeper
* Steps to fix:
  * SSH in to the webapp instance
  * cd /var/app/current
  * BUNDLE_PATH=/opt/rubies/ruby-2.3.4/lib/ruby/gems/2.3.0/ bundle exec rake zookeeper:upload
  * Log on to each of the solr instances - do this on the leader LAST
  * sudo docker ps (to get the solr container ID)
  * sudo docker restart <container-id>
  * A new log file in /var/log/containers will be started on restart of solr, wait for this to be created and verify configs were pulled from zookeeper

Notes
* The rake task being used in the above steps is here: https://github.com/samvera-labs/hyku/blob/master/lib/tasks/zookeeper.rake
  * It points to the solr settings here: https://github.com/samvera-labs/hyku/blob/master/config/settings.yml
* Which in turn points to the solr configs (that are uploaded to zookeeper) here: https://github.com/samvera-labs/hyku/tree/master/solr/config
